### PR TITLE
Added support for build command and CSS is now injected into the dom-module and minified.

### PR DESCRIPTION
**Pull request by herkulano**

### CODE REVIEW

**Comment by herkulano** [comment]
CSS is now injected into the dom-module and minified.
Added documentation.

**Comment by Hypercubed** [comment]
Thank you @herkulano .  I have thought a lot about these changes and I think I am going to hold off on this for the moment.  The systemjs-plugin-html is a generic SystemJS plugin for doing HTML imports in an application, not necessarily for building web components.  I think what you have added is more beneficial as a separate element builder tool along the lines of Polymer/vulcanize.

Without this change non-sfx bundling in application works fine.  The developer will need to copy html files as part of the build step, which I presume they are already doing.  With this change one level of html will be bundled into an element.html file but HTML imports (via link tag) inside these imported files do not get included... this means that the developer still needs to copy html files during the build step.

Feel free to comment back if you I am missing something.

**Comment by Hypercubed** [comment]
One more comment to consider:

There is the added difficulty that if you try to register the same component twice in polymer you will get a runtime error.  Using HTML imports this is avoided because HTML imports with the same href are deduplicated.    For example if element A imports element B via HTML import link tag and the developers application imports both element A and element B using the plugin then generates the `element.html` bundle, element B will be imported twice with two different urls and throws an error.  This may come up even without bundling but it is something we should address.

**Comment by herkulano** [comment]
> I think what you have added is more beneficial as a separate element builder tool along the lines of Polymer/vulcanize.

That implies another build step and more tooling.

> Without this change non-sfx bundling in application works fine. The developer will need to copy html files as part of the build step, which I presume they are already doing.

That means a lot of work handling the html files that could be avoided by a sfx bundle, plus minifying them. That's why gulp, grunt, etc are so popular, to avoid handling the files for production yourself.

> With this change one level of html will be bundled into an element.html file but HTML imports (via link tag) inside these imported files do not get included... this means that the developer still needs to copy html files during the build step.

The bundling works only for components that don't use the HTML Imports inside the html and make use of SystemJS instead. It's an opinionated way. If you do things this way it works fine. Otherwise you might be better off not using jspm at all and go for the bower + Polymer/vulcanize way, which is also an opinionated way. :smile: 

> There is the added difficulty that if you try to register the same component twice in polymer you will get a runtime error. Using HTML imports this is avoided because HTML imports with the same href are deduplicated. For example if element A imports element B via HTML import link tag and the developers application imports both element A and element B using the plugin then generates the element.html bundle, element B will be imported twice with two different urls and throws an error. This may come up even without bundling but it is something we should address.

This is actually not happening because of it's using SystemJS imports, it takes care of this, both in bundled-sfx and non bundled versions. I made a few changes to test this:
https://github.com/herkulano/systemjs-plugin-html

**Comment by Hypercubed** [comment]
@herkulano Can you please resubmit this PR with just the html-builder.js file added to the latest master?  I want to pull this file and keep record of you as a contributor.

**Comment by herkulano** [comment]
@Hypercubed cool, made the changes and it's ready to merge. 

Didn't test it and didn't add the dependencies in package.json: "clean-css", "minimize".

Had some trouble merging the fork, so there are a few files that are in the PR that are simply copied, no change was made, but they still appear in the merge. :(

**Comment by Hypercubed** [comment]
Thanks, don't worry about the dependencies.  I'll handle it.  I might try to use vulcanize in the builder.

**Pull request merged**
